// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/game/": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "create new game.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "create new game.",
                "parameters": [
                    {
                        "description": "request",
                        "name": "game",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateGameBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateGameResponse"
                        }
                    }
                }
            }
        },
        "/game/{gameId}/board": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "get board.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "board"
                ],
                "summary": "get board.",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "gameId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetBoardResponse"
                        }
                    }
                }
            }
        },
        "/game/{gameId}/give-up": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "do give-up.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "give-up"
                ],
                "summary": "do give-up.",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "gameId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Game"
                        }
                    }
                }
            }
        },
        "/game/{gameId}/history": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "get history.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "get history.",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "gameId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetHistoryResponse"
                        }
                    }
                }
            }
        },
        "/game/{gameId}/move": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "do move.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "move"
                ],
                "summary": "do move.",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "gameId",
                        "in": "path"
                    },
                    {
                        "description": "move",
                        "name": "move",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DoMoveBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Move"
                        }
                    }
                }
            }
        },
        "/session/": {
            "post": {
                "description": "create new session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "create new session.",
                "parameters": [
                    {
                        "description": "request",
                        "name": "session",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateSessionResponse"
                        }
                    }
                }
            }
        },
        "/user/": {
            "post": {
                "description": "create new user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "create new user.",
                "parameters": [
                    {
                        "description": "request",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BoardCellEntity": {
            "type": "object",
            "properties": {
                "figureId": {
                    "type": "integer"
                },
                "indexCell": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateGameBody": {
            "type": "object",
            "properties": {
                "isWhite": {
                    "type": "boolean"
                }
            }
        },
        "dto.CreateGameResponse": {
            "type": "object",
            "properties": {
                "blackKingCastling": {
                    "type": "boolean"
                },
                "blackRookACastling": {
                    "type": "boolean"
                },
                "blackRookHCastling": {
                    "type": "boolean"
                },
                "blackUserId": {
                    "type": "integer"
                },
                "gameId": {
                    "type": "integer"
                },
                "isCheckBlack": {
                    "type": "boolean"
                },
                "isCheckWhite": {
                    "type": "boolean"
                },
                "isEnded": {
                    "type": "boolean"
                },
                "isStarted": {
                    "type": "boolean"
                },
                "lastPawnMove": {
                    "type": "integer"
                },
                "side": {
                    "type": "boolean"
                },
                "whiteKingCastling": {
                    "type": "boolean"
                },
                "whiteRookACastling": {
                    "type": "boolean"
                },
                "whiteRookHCastling": {
                    "type": "boolean"
                },
                "whiteUserId": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateSessionRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.CreateSessionResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.CreateUserRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.CreateUserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.DoMoveBody": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "newFigure": {
                    "type": "integer"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "dto.GetBoardResponse": {
            "type": "object",
            "properties": {
                "boardCells": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.BoardCellEntity"
                    }
                }
            }
        },
        "dto.GetHistoryResponse": {
            "type": "object",
            "properties": {
                "moves": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Move"
                    }
                }
            }
        },
        "models.Game": {
            "type": "object",
            "properties": {
                "blackKingCastling": {
                    "type": "boolean"
                },
                "blackRookACastling": {
                    "type": "boolean"
                },
                "blackRookHCastling": {
                    "type": "boolean"
                },
                "blackUserId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isCheckBlack": {
                    "type": "boolean"
                },
                "isCheckWhite": {
                    "type": "boolean"
                },
                "isEnded": {
                    "type": "boolean"
                },
                "isStarted": {
                    "type": "boolean"
                },
                "lastPawnMove": {
                    "type": "integer"
                },
                "side": {
                    "type": "boolean"
                },
                "whiteKingCastling": {
                    "type": "boolean"
                },
                "whiteRookACastling": {
                    "type": "boolean"
                },
                "whiteRookHCastling": {
                    "type": "boolean"
                },
                "whiteUserId": {
                    "type": "integer"
                }
            }
        },
        "models.Move": {
            "type": "object",
            "properties": {
                "figureId": {
                    "type": "integer"
                },
                "from_id": {
                    "type": "integer"
                },
                "gameId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isCheckBlack": {
                    "type": "boolean"
                },
                "isCheckWhite": {
                    "type": "boolean"
                },
                "killedFigureId": {
                    "type": "integer"
                },
                "moveNumber": {
                    "type": "integer"
                },
                "newFigureId": {
                    "type": "integer"
                },
                "to_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "description": "JWT security accessToken. Please add it in the format \"Bearer {AccessToken}\" to authorize your requests.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Fiber Swagger Example API",
	Description:      "This is a sample server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
