version: "3.7"

services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 5
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'test'

    command: postgres -c max_connections=20 -c shared_buffers=200MB
#    ports:
#        - "8090:5432"
    networks:
      - infra

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_USERNAME=user
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  application:
    depends_on:
      postgres:
          condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - infra
    env_file: .env



networks:
  infra:
    driver: bridge