name: Main PR Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  GO_VERSION: '1.24.2'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: make test-logic

  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install deps linter
        run:  make install-deps

      - name: Run linter
        run:  make lint

  vuln:
    name: Check Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install deps linter
        run:  make install-deps

      - name: Check vulnerabilities
        run: make vuln